GET http://localhost:5000/auth/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzhiODQ2MWRjYWQxM2JhYzlkMTNjM2MiLCJpYXQiOjE3MzcxOTg4MTUsImV4cCI6MTczNzIwMjQxNX0.ce0FqOCfp6QX4K75jdcwuKzu3aX1wa6HEqZikRLL2vM

{
    "email": "dhanushsai1467@gmail.com",
    "password": "Dhanush@2007",
    "username": "dhanush"
}
###
POST http://localhost:5000/auth/signup
content-type: application/json

{
    "email": "dhanushsai1467@gmail.com",
    "password": "Dhanush@2007",
    "username": "dhanush"
}
###
POST http://localhost:5000/auth/login
content-type: application/json

{
    "email": "dhanushsai1467@gmail.com",
    "password": "Dhanush@2007",
    "username": "dhanush"
}
###
POST http://localhost:5000/conversation/678b8461dcad13bac9d13c3c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzhiOWQxNDg3MGViOGNhMzllMmViYTAiLCJpYXQiOjE3MzcyMDY5MDMsImV4cCI6MTczNzIxMDUwM30.o7CfDQGOG483zu1ikTHTTg7MwFOn7ZH9Crn3HLI2bVA
content-type: application/json

{
    "participants": ["678b8461dcad13bac9d13c3c","678b9d14870eb8ca39e2eba0"],
    "lastMessage": {
        "message":"user d && user e"
    }
}
###
GET http://localhost:5000/conversation/3789236e978637399bb6be28
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Nzg5MjNkMTk3ODYzNzM5OWJiNmJlMjciLCJpYXQiOjE3MzcwODc4MjcsImV4cCI6MTczNzA5MTQyN30.GTdGTIRYHFOCp8mcTg0mH_QzXsv3XgTJ5LMMGbMnkZk
content-type: application/json

{
    "participants": ["alkjsfd;dfjkadfasdfv","lkahsdlfkhvwelkfjnhas"],
    "lastMessage": {
        "message":"Help me"
    }
}
###
DELETE  http://localhost:5000/conversation/3789236e978637399bb6be28
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Nzg5MjNkMTk3ODYzNzM5OWJiNmJlMjciLCJpYXQiOjE3MzcwODc4MjcsImV4cCI6MTczNzA5MTQyN30.GTdGTIRYHFOCp8mcTg0mH_QzXsv3XgTJ5LMMGbMnkZk
content-type: application/json

{
    "participants": ["alkjsfd;dfjkadfasdfv","lkahsdlfkhvwelkfjnhas"],
    "lastMessage": {
        "message":"Help me"
    }
}
###
POST  http://localhost:5000/message/3789236e978637399bb6be28
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Nzg5MjNkMTk3ODYzNzM5OWJiNmJlMjciLCJpYXQiOjE3MzcxOTI3ODEsImV4cCI6MTczNzE5NjM4MX0.YgIwFoAjAtA_LH1giajoSb5_bv25Dty1C06lqPQnICw
content-type: application/json

{
    "conversationId": "6789dccc97f472291da24030",
    "message": "askjdfalskdf are you, dhanush"
}
###
GET  http://localhost:5000/message/3789236e978637399bb6be28
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Nzg5MjNkMTk3ODYzNzM5OWJiNmJlMjciLCJpYXQiOjE3MzcxOTI3ODEsImV4cCI6MTczNzE5NjM4MX0.YgIwFoAjAtA_LH1giajoSb5_bv25Dty1C06lqPQnICw
content-type: application/json

